language: node_js
node_js:
  - "10"
install:
  - npm install esm
  - npm install -g coveralls standard tape tap-spec nyc
script:
  - npm run lint
  - npm run test:cov
cache:
  directories:
  - "node_modules"
after_success: npm run coverage
